### ISSUE TITLE
Cannot get any flights to track

### ISSUE THREAD

**Issue by ConMinGit** [c0wsaysmoo/plane-tracker-rgb-pi#4]
I previously had the project up and working brilliantly but then encountered a bug where a flight would get stuck permanently on the panel. 
I've just recently completely reinstalled the project from scratch and cannot get any flights to show at all for some reason. I can get the weather scene with clock etc working fine but it will not display any flights going over head. Any ideas where I could be going wrong here?

**Comment by c0wsaysmoo** [comment]
Curious. I do know the bug you're talking about but it has been fixed as
far as I know. When did you most recently pull the files?

**Comment by c0wsaysmoo** [comment]
I do know that with the newest os for raspberry pi (bookworm) you have to install things differently

**Comment by ConMinGit** [comment]
I've tried 32 and 64 bit bullseye with a fresh gut pull and I'm still getting no flight tracking. Everything else seems to be working fine though and I'm not getting any errors when running its-a-plane.py

**Comment by c0wsaysmoo** [comment]
Only thing I can think of offhand is the flightradarapi wasn't installed.
You can try running

pip3 show FlightRadarAPI

That'll tell you if it's installed

When you use git it pulls my code but it doesn't pull the flightradarapi
that has to be installed separately.
If it's not installed you'll have to run

sudo pip3 install FlightRadarAPI

**Comment by ConMinGit** [comment]
Yeah I have everything installed, both pytz requests and the Flight Radar API.

I'm determined to figure this out though, I'll report back when I find my issue.

**Comment by c0wsaysmoo** [comment]
No worries not trying to downplay it just trying to rule stuff out. I'm on
a work trip until Thursday but I'll poke at the GitHub and see if anything
stands out. Problem is I've changed it so much over time I'm not 100% sure
what version I have posted. When did you first build the project? Are you
using imperial or metric units? Just trying to get an idea on your setup

**Comment by ConMinGit** [comment]
Oh no worries, im more just trying to figure it out for my own sanity.

I first had it set up about 3 months ago and it worked perfectly until the last few weeks when flights were getting stuck. Then I the last couple of days I started from scratch and pulled all the files again and can't get the plane tracking to appear.

I might try Colin Waddells project and see if I can get that to show anything to rule some stuff out.

I'm on a pi zero 2 w,
Debian bullseye
Metric, 24hr
Adafruit hat with Solder bridge

**Comment by c0wsaysmoo** [comment]
Curious indeed. There was a moment when there was a glitch where the plane
would get stuck but only in certain circumstances I think when there were
multiple flights. This morning I saw a flt so I know mine is currently
working but again I'm not sure what code mine is on vs the one I have
uploaded. I do have it running on a pi zero since the pi zero 2 you have to
solder on the header (as far as I know)

**Comment by c0wsaysmoo** [comment]
Out of curiosity, did you get it to work? I'll try and upload my current
version tomorrow morning and see if that works.

**Comment by ConMinGit** [comment]
It's something to do with rate limiting and establishing the connection on FlightRadarAPI, it's above my paygrade haha. I see Colin Waddell must have had the same issues as he added a few lines into overhead.py to try and catch it.

I haven't got around to doing it myself yet though.

**Comment by c0wsaysmoo** [comment]
ok i just uploaded whats on mine. if you want can you send me your config file so i can test it on mine

**Comment by ConMinGit** [comment]
I just pulled your new version and it's the same, still getting weather but no flight details.

Which version of FlightRadarAPI are you running out of interest? I wonder if something has changed.

**Comment by c0wsaysmoo** [comment]
pip3 show FlightRadarAPI
Name: FlightRadarAPI
Version: 1.2.3
Summary: API for FlightRadar24
Home-page: https://github.com/JeanExtreme002/FlightRadarAPI
Author: Jean Loui Bernard Silva de Jesus
Author-email:
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: Brotli, Deprecated, requests
for my main one and

Name: FlightRadarAPI
Version: 1.3.12
Summary: API for FlightRadar24
Home-page:
Author:
Author-email: Jean Loui Bernard Silva de Jesus ***@***.***>
License:
Location: /home/flight/.local/lib/python3.11/site-packages
Requires: brotli, requests
Required-by:

for my desk both of them are working.
if youre getting a rate limit error. perhaps you can try making a smaller
box and placing it in a different location  (pull up the flight radar
website and search for an area with fewer planes and try putting it there
just see if you can get any planes)

**Comment by c0wsaysmoo** [comment]
ah so i did a fresh install and got the same issue as you. I looked over Colin's code and figured out the difference so it should work now

**Comment by ConMinGit** [comment]
Thank god it wasn't just me doing something stupid! 

Just did a fresh pull there and everything is back working perfectly, thanks for all the help.

**Comment by c0wsaysmoo** [comment]
Thanks but it's thanks to Colin. Not sure I would have figured it out.
